# Continuous integration procedure for AppVeyor
# Based on https://github.com/rmcgibbo/python-appveyor-conda-example

environment:
  matrix:
      - PYTHON_VERSION: "3.6"
        MINICONDA: "C:\\Miniconda36-x64"
        PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # these correspond to folder naming of miniconda installs on appveyor.  See
  # https://www.appveyor.com/docs/installed-software#python
  - if "%PYTHON_VERSION%" == "3.6" set "BASE_PYTHON_VERSION=36"
  - if "%PYTHON_ARCH%" == "64" set "ARCH_LABEL=-x64"
  # These are already installed on appveyor.  Update them.
  - set "CONDA_ROOT=C:\Miniconda%BASE_PYTHON_VERSION%%ARCH_LABEL%"
  - set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"

  # Dependencies and package install
  - ps: Start-FileDownload 'https://d37drm4t2jghv5.cloudfront.net/distributions/25.1.1/windows/windows_x64_64.exe'
  - windows_x64_64.exe /SP- /VERYSILENT /NORESTART /DIR=.\gams /NOICONS
  - "SET PATH=%cd%\\gams;%PATH%"
  - conda install --yes -c conda-forge ixmp xlsxwriter xlrd
  - conda remove --force --yes ixmp

  - git clone https://github.com/iiasa/ixmp.git
  - cd ixmp && python setup.py install && cd ..

  - pip install .[reporting]

build: false

test_script:
  - conda install --yes -c conda-forge pytest
  - pytest -v tests
  - messageix-config --model_path=message_ix\\model

on_success:
  - echo Build succesful!
