name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  # 05:00 UTC = 06:00 CET = 07:00 CEST
  - cron: "0 5 * * *"

jobs:
  lint:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
    - name: Check out ixmp
      uses: actions/checkout@v3
      with:
        repository: iiasa/ixmp
        # For PRs that depend on an ixmp PR branch, uncomment the following 2
        # lines and adjust to suit:
        # repository: USERNAME/ixmp
        # ref: issue/999
        path: ixmp

    - name: Check out message_ix
      uses: actions/checkout@v3
      with:
        path: message_ix

    - uses: actions/setup-python@v4
      # This should match the "Latest version testable on GitHub Actions"
      # in pytest.yaml
      # with:
      #   python-version: "3.10"

    - name: Upgrade pip, wheel
      id: pip
      run: |
        python -m pip install --upgrade pip wheel
        # Locate pip cache directory
        echo "::set-output name=cache-dir::$(pip cache dir)"

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip.outputs.cache-dir }}
        key: lint-${{ runner.os }}

    - name: Check "black" code style
      working-directory: message_ix
      run: |
        pip install black
        black --check .

    - name: Lint with flake8 & isort
      working-directory: message_ix
      run: |
        pip install flake8 isort
        flake8 --count --max-complexity=38 --show-source --statistics
        isort --check-only .

    - name: Check typing with mypy
      working-directory: message_ix
      # Point to ixmp code for its type hints, without installing
      env:
        MYPYPATH: "../ixmp/"
      # Also install type stubs and full packages that provide type hints
      run: |
        pip install mypy genno sphinx types-pkg_resources types-requests types-PyYAML
        mypy --show-error-codes .
