name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # For setuptools-scm. With fetch --tags below, this ensures that
  # enough history is fetched to contain the latest tag, so that
  # setuptools-scm can generate the version number. Update:
  # - See https://github.com/iiasa/message_ix/releases, at "NN commits to
  #   master since this release". The value should be at least equal to
  #   NN + the number of commits on any PR branch.
  # - Reset to a lower value, e.g. 100, after a new release.
  depth: 100

jobs:
  lint:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
    - name: Check out ixmp
      uses: actions/checkout@v2
      with:
        repository: iiasa/ixmp
        # For PRs that depend on an ixmp PR branch, uncomment the following 2
        # lines and adjust to suit:
        # repository: USERNAME/ixmp
        # ref: issue/999
        path: ixmp
        fetch-depth: ${{ env.depth }}

    - name: Check out message_ix
      uses: actions/checkout@v2
      with:
        path: message_ix
        fetch-depth: ${{ env.depth }}

    - name: Fetch tags (for setuptools-scm)
      run: |
        (cd ixmp; git fetch --tags --depth=${{ env.depth }})
        (cd message_ix; git fetch --tags --depth=${{ env.depth }})
      shell: bash

    - uses: actions/setup-python@v2
      with:
        # This should match the "Latest version testable on GitHub Actions"
        # in pytest.yml
        python-version: "3.8"

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/Library/Caches/pip
          ~/appdata/local/pip/cache
        key: lint-${{ runner.os }}

    - name: Upgrade pip, wheel
      run: python -m pip install --upgrade pip wheel

    - name: Check "black" code style
      working-directory: message_ix
      run: |
        pip install black
        black --check .

    - name: Lint with flake8 & isort
      working-directory: message_ix
      run: |
        pip install flake8 isort
        flake8 --count --max-complexity=38 --show-source --statistics
        isort --check-only .

    - name: Check typing with mypy
      working-directory: message_ix
      # Point to ixmp code for its type hints, without installing
      env:
        MYPYPATH: "../ixmp/"
      # Also install packages that provide type hints
      run: |
        pip install mypy genno sphinx
        mypy .

    - name: Test package build
      working-directory: message_ix
      run: |
        pip install twine wheel
        python3 setup.py bdist_wheel sdist
        twine check dist/*
