name: Test MESSAGEix-GLOBIOM scenarios
# This workflow is a stripped-down version of pytest.yaml, with multi-OS
# features removed.

on:
  # Uncomment these two lines for debugging, but leave them commented on 'main'
  # pull_request:
  #   branches: [ main ]
  schedule:
  # 05:00 UTC = 06:00 CET = 07:00 CEST
  - cron: "0 5 * * *"
  pull_request_target:
    paths:
    - '**.gms'
    - '**.gpr'
    - '**.gdx'
    types:
    - labeled

env:
  depth: 100  # See description in pytest.yaml
  # Version used until 2024-11-20; disabled
  # gams-version: 29.1.0
  # First version including a macOS arm64 distribution
  gams-version: 43.4.1
  os: ubuntu-latest
  python-version: "3.13"

permissions: {contents: read}

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
    - name: Check out message_ix
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ env.depth }}

    - name: Fetch tags (for setuptools-scm)
      run: git fetch --tags --depth=${{ env.depth }}

    - name: Set up uv, Python
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Cache GAMS installer and snapshot files
      uses: actions/cache@v4
      with:
        path: |
          gams
          .pytest_cache/d/snapshots
        key: nightly-gams${{ env.gams-version }}

    - uses: iiasa/actions/setup-gams@main
      with:
        version: ${{ env.gams-version }}
        license: ${{ secrets.GAMS_LICENSE }}

    - name: Install package and dependencies
      run: |
        uv pip install --upgrade \
          "ixmp[tests] @ git+https://github.com/iiasa/ixmp.git@main" \
          .[tests]

    - name: Run test suite using pytest
      env:
        MESSAGE_IX_ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
      run: |
        pytest message_ix -m nightly \
          --color=yes --durations=20 -rA --verbose
